'use client';

import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';

import { fit, type DeckMode } from './boot';

/**
 * The deck's controller. Every slide is authored on a fixed 1920 x 1080 canvas and the whole
 * stage is scaled to the window, so a slide looks the same on a laptop, a projector and in the
 * PDF. On a narrow portrait screen the slides stack instead and the page scrolls.
 *
 * Keys: arrows, space, page up and down, home and end move; F is full screen; O opens the
 * overview and Escape closes it. The slide number lives in the URL hash (#4), so a link can open any slide.
 */

/** The printed deck, regenerated by scripts/pitch-pdf.sh from this page's print layout. */
export const PDF_HREF = '/hunch-pitch-deck.pdf';

function slideFromHash(count: number): number {
  const n = Number.parseInt(window.location.hash.replace(/^#\/?/, ''), 10);
  return Number.isFinite(n) && n >= 1 && n <= count ? n - 1 : 0;
}

export function Deck({ slides, labels }: { slides: React.ReactNode[]; labels: string[] }) {
  const count = slides.length;
  const [index, setIndex] = useState(0);
  const [mode, setMode] = useState<DeckMode>('deck');
  const [overview, setOverview] = useState(false);
  const [idle, setIdle] = useState(false);
  const wheelLock = useRef(0);
  const touch = useRef<{ x: number; y: number } | null>(null);
  const idleTimer = useRef<number | undefined>(undefined);

  const go = useCallback((next: number) => setIndex(() => Math.max(0, Math.min(count - 1, next))), [count]);
  const step = useCallback((delta: number) => setIndex((current) => Math.max(0, Math.min(count - 1, current + delta))), [count]);

  // Scale to the window, before paint and on every resize.
  useLayoutEffect(() => {
    const root = document.documentElement;
    const apply = (): void => {
      const next = fit(window.innerWidth, window.innerHeight);
      root.dataset.deckMode = next.mode;
      root.style.setProperty('--deck-scale', String(next.scale));
      setMode(next.mode);
    };
    apply();
    window.addEventListener('resize', apply);
    return () => {
      window.removeEventListener('resize', apply);
      delete root.dataset.deckMode;
      root.style.removeProperty('--deck-scale');
    };
  }, []);

  // The hash is the slide number, both ways.
  useEffect(() => {
    setIndex(slideFromHash(count));
    const onHash = (): void => setIndex(slideFromHash(count));
    window.addEventListener('hashchange', onHash);
    return () => window.removeEventListener('hashchange', onHash);
  }, [count]);

  useEffect(() => {
    const hash = `#${index + 1}`;
    if (window.location.hash !== hash) window.history.replaceState(null, '', hash);
    document.title = `${labels[index] ?? 'Hunch'} · Hunch`;
  }, [index, labels]);

  const toggleFullscreen = useCallback(() => {
    if (document.fullscreenElement) void document.exitFullscreen();
    else void document.documentElement.requestFullscreen?.().catch(() => undefined);
  }, []);

  // Keyboard. A stacked deck scrolls like a page, so it keeps the browser's own keys.
  useEffect(() => {
    const onKey = (event: KeyboardEvent): void => {
      if (event.metaKey || event.ctrlKey || event.altKey || mode !== 'deck') return;
      const target = event.target;
      if (target instanceof Element && target.closest('input, textarea, select, [contenteditable="true"]')) return;
      const key = event.key;
      if (key === 'o' || key === 'O') setOverview((open) => !open);
      else if (overview && (key === 'Escape' || key === 'Enter')) setOverview(false);
      else if (['ArrowRight', 'ArrowDown', 'PageDown', ' '].includes(key) || (key === 'Enter' && !overview)) step(1);
      else if (['ArrowLeft', 'ArrowUp', 'PageUp', 'Backspace'].includes(key)) step(-1);
      else if (key === 'Home') go(0);
      else if (key === 'End') go(count - 1);
      else if (key === 'f' || key === 'F') toggleFullscreen();
      else if (/^[1-9]$/.test(key)) go(Number(key) - 1);
      else return;
      event.preventDefault();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [count, go, mode, overview, step, toggleFullscreen]);

  // Wheel and trackpad: one slide per gesture.
  const onWheel = useCallback(
    (event: React.WheelEvent) => {
      if (mode !== 'deck' || overview) return;
      const delta = Math.abs(event.deltaY) > Math.abs(event.deltaX) ? event.deltaY : event.deltaX;
      if (Math.abs(delta) < 24) return;
      const now = Date.now();
      if (now < wheelLock.current) return;
      wheelLock.current = now + 650;
      step(delta > 0 ? 1 : -1);
    },
    [mode, overview, step],
  );

  // Swipe.
  const onTouchStart = useCallback((event: React.TouchEvent) => {
    const t = event.touches[0];
    touch.current = t === undefined ? null : { x: t.clientX, y: t.clientY };
  }, []);
  const onTouchEnd = useCallback(
    (event: React.TouchEvent) => {
      const start = touch.current;
      const t = event.changedTouches[0];
      touch.current = null;
      if (mode !== 'deck' || overview || start === null || t === undefined) return;
      const dx = t.clientX - start.x;
      const dy = t.clientY - start.y;
      if (Math.abs(dx) > 48 && Math.abs(dx) > Math.abs(dy)) step(dx < 0 ? 1 : -1);
    },
    [mode, overview, step],
  );

  // A click on the slide moves on (the left fifth goes back), unless it lands on a link or a control.
  const onStageClick = useCallback(
    (event: React.MouseEvent) => {
      if (mode !== 'deck' || overview) return;
      if ((event.target as HTMLElement).closest('a, button')) return;
      if ((window.getSelection()?.toString() ?? '') !== '') return;
      step(event.clientX < window.innerWidth / 5 ? -1 : 1);
    },
    [mode, overview, step],
  );

  // The controls fade out while the deck is being presented and come back on any movement.
  const wake = useCallback(() => {
    setIdle(false);
    window.clearTimeout(idleTimer.current);
    idleTimer.current = window.setTimeout(() => setIdle(true), 2600);
  }, []);
  useEffect(() => {
    wake();
    window.addEventListener('mousemove', wake);
    return () => {
      window.removeEventListener('mousemove', wake);
      window.clearTimeout(idleTimer.current);
    };
  }, [wake]);

  return (
    <div className="pitch" data-overview={overview ? 'true' : undefined} onWheel={onWheel} onTouchStart={onTouchStart} onTouchEnd={onTouchEnd}>
      <div className="pitch-viewport" onClick={onStageClick}>
        <div className="pitch-stage">
          {slides.map((slide, i) => (
            <section
              key={labels[i] ?? i}
              id={`slide-${i}`}
              className="pitch-frame"
              aria-label={`Slide ${i + 1} of ${count}: ${labels[i] ?? ''}`}
              aria-hidden={mode === 'deck' && i !== index ? true : undefined}
              data-state={i === index ? 'active' : i < index ? 'past' : 'future'}
            >
              <div className="pitch-slide">{slide}</div>
            </section>
          ))}
        </div>
      </div>

      {overview ? (
        <div className="pitch-overview" role="dialog" aria-label="All slides">
          <div className="pitch-overview-grid">
            {slides.map((slide, i) => (
              <button
                key={labels[i] ?? i}
                type="button"
                className="pitch-thumb"
                data-current={i === index ? 'true' : undefined}
                onClick={() => {
                  go(i);
                  setOverview(false);
                }}
              >
                <span className="pitch-thumb-canvas" aria-hidden>
                  <span className="pitch-slide" data-static>
                    {slide}
                  </span>
                </span>
                <span className="pitch-thumb-label">
                  <span className="num">{String(i + 1).padStart(2, '0')}</span> {labels[i]}
                </span>
              </button>
            ))}
          </div>
        </div>
      ) : null}

      <p className="sr-only" aria-live="polite">
        {mode === 'deck' ? `Slide ${index + 1} of ${count}: ${labels[index] ?? ''}` : ''}
      </p>

      <div className="pitch-progress" aria-hidden>
        <span style={{ transform: `scaleX(${(index + 1) / count})` }} />
      </div>

      {mode === 'stack' ? (
        <nav className="pitch-controls" aria-label="Deck controls">
          <span className="pitch-hint">Turn your phone sideways to present</span>
          <a href={PDF_HREF} download aria-label="Download as PDF" className="pitch-pdf">
            PDF
          </a>
        </nav>
      ) : (
        <nav className="pitch-controls" data-idle={idle && !overview ? 'true' : undefined} aria-label="Deck controls">
          <button type="button" onClick={() => step(-1)} disabled={index === 0} aria-label="Previous slide">
            <Chevron flip />
          </button>
          <span className="pitch-count">
            <span className="num text-paper">{String(index + 1).padStart(2, '0')}</span>
            <span className="num text-faint"> / {String(count).padStart(2, '0')}</span>
            <span className="pitch-count-label">{labels[index]}</span>
          </span>
          <button type="button" onClick={() => step(1)} disabled={index === count - 1} aria-label="Next slide">
            <Chevron />
          </button>
          <span className="pitch-divider" aria-hidden />
          <button type="button" onClick={() => setOverview((open) => !open)} aria-label="All slides" aria-pressed={overview}>
            <GridIcon />
          </button>
          <button type="button" onClick={toggleFullscreen} aria-label="Full screen" className="pitch-hide-narrow">
            <ExpandIcon />
          </button>
          <a href={PDF_HREF} download aria-label="Download as PDF" className="pitch-pdf">
            PDF
          </a>
        </nav>
      )}
    </div>
  );
}

function Chevron({ flip = false }: { flip?: boolean }) {
  return (
    <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden style={flip ? { transform: 'scaleX(-1)' } : undefined}>
      <path d="M9 5l7 7-7 7" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

function GridIcon() {
  return (
    <svg viewBox="0 0 24 24" width="17" height="17" aria-hidden>
      {[3, 13].flatMap((x) => [3, 13].map((y) => <rect key={`${x}-${y}`} x={x} y={y} width="8" height="8" rx="2" fill="none" stroke="currentColor" strokeWidth="1.8" />))}
    </svg>
  );
}

function ExpandIcon() {
  return (
    <svg viewBox="0 0 24 24" width="17" height="17" aria-hidden>
      <path d="M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}
