// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Vm} from "forge-std/Vm.sol";
import {console} from "forge-std/Test.sol";
import {ForkBase} from "./ForkBase.sol";
import {RH, IUSDG, IChainlinkProxy} from "../../script/RH.sol";
import {HunchVPM, IERC20} from "../../src/HunchVPM.sol";
import {StockRoundResolver} from "../../src/StockRoundResolver.sol";
import {HunchMarketFactory} from "../../src/HunchMarketFactory.sol";
import {IERC20Like} from "../../src/interfaces/IERC20Like.sol";
import {MockUSDG} from "../../src/mocks/MockUSDG.sol";
import {MockAggregator} from "../../src/mocks/MockAggregator.sol";
import {MockStockToken} from "../../src/mocks/MockStockToken.sol";

/// @title  T7g: gas of the product contracts on a fork of Robinhood Chain → GAS.md (fork section)
/// @notice The scenario of test/HunchGas.t.sol (the same calls in the same order), measured on
///         the fork with every call executed as ITS OWN TRANSACTION (forge's isolate mode, set
///         inline below): fresh warm/cold state and fresh original storage values per call, so
///         each figure is what that transaction's receipt would show (21,000 base + calldata +
///         execution, net of the EIP-3529 refund). Run twice:
///           mocks      the local setup (MockUSDG, MockAggregator, MockStockToken);
///           real USDG  the Paxos USDG proxy in place of MockUSDG (facets, freeze list, pause,
///                      rewards accounting); feed and Stock Token stay mocks so the market
///                      resolves deterministically;
///         plus `resolve` on the REAL NVDA Chainlink proxy and REAL NVDA Stock Token (a beacon
///         proxy), proving the latest real round and the one before it. The execution column
///         (receipt − 21,000 − calldata, before the refund) is what the budgets of
///         docs/spec/03-contracts.md §Gas and the local table measure. It writes
///         test/fork/GAS-FORK.md and replaces the fork section of GAS.md (after the marker line):
///           RH_RPC_URL=https://rpc.mainnet.chain.robinhood.com forge test --root contracts --match-contract ForkGasTest -vv
///         (`vm.cool` stops working once state-diff recording is used in forge 1.5, and the
///         accounts real USDG and the real feed touch are not all known up front: isolate mode
///         measures them all as a real transaction would.)
contract ForkGasTest is ForkBase {
    string internal constant MARKER =
        "<!-- fork-gas: generated by test/fork/ForkGas.t.sol; everything below is rewritten -->";

    uint256 internal constant BETTOR_PK = 0xB377;
    address internal bettor = vm.addr(BETTOR_PK);
    address internal safe = makeAddr("safe");
    address internal keeper = makeAddr("keeper");
    address internal relayer = makeAddr("relayer");

    struct Measured {
        uint256 receipt; // gas used as a receipt shows it: total − min(refund, total / 5)
        uint256 execution; // total − 21,000 − calldata, before the refund
    }

    // the run in progress
    HunchVPM internal vpm;
    StockRoundResolver internal resolver;
    HunchMarketFactory internal factory;
    IUSDG internal token;
    MockAggregator internal feed;
    MockStockToken internal stock;
    bool internal realToken;
    uint64 internal strike;
    uint64 internal bell;
    uint256 internal id;
    bytes32 internal specId;
    bytes internal lastReturn;

    string[] internal labels;
    uint256[] internal budgets;
    Measured[] internal mockGas;
    Measured[] internal realGas;
    Measured internal realResolve;
    Measured internal realFlat;
    string internal realFeedOutcome;
    uint256 internal forkBlock;
    uint256 internal forkTime;

    function setUp() public {
        if (!_forkOrSkip()) return;
        forkBlock = block.number;
        forkTime = block.timestamp;
    }

    /// forge-config: default.isolate = true
    /// forge-config: ci.isolate = true
    function test_GenerateForkGasReport() public {
        _realFeedRows(); // first, at the fork's own time: its proofs are the latest real rounds
        _run(false);
        _run(true);
        _write();
    }

    // ================================================================== measuring

    /// @dev One call as its own transaction (isolate mode), from `from`.
    function _measure(address from, address target, bytes memory data) internal returns (Measured memory m) {
        vm.prank(from);
        (bool ok, bytes memory ret) = target.call(data);
        if (!ok) {
            assembly ("memory-safe") {
                revert(add(ret, 0x20), mload(ret))
            }
        }
        Vm.Gas memory g = vm.lastCallGas();
        // gasRefunded is an int64 that is never negative at the end of a transaction
        // forge-lint: disable-next-line(unsafe-typecast)
        uint256 refunded = g.gasRefunded > 0 ? uint256(uint64(g.gasRefunded)) : 0;
        uint256 refund = refunded < g.gasTotalUsed / 5 ? refunded : g.gasTotalUsed / 5;
        m.receipt = g.gasTotalUsed - refund;
        m.execution = g.gasTotalUsed - 21_000 - _calldataGas(data);
        lastReturn = ret;
    }

    function _calldataGas(bytes memory data) internal pure returns (uint256 gas) {
        for (uint256 i = 0; i < data.length; i++) {
            gas += data[i] == 0 ? 4 : 16;
        }
    }

    /// @dev Record a measurement; the first run fills the labels and the mocks column.
    function _row(string memory label, Measured memory m, uint256 budget) internal {
        if (!realToken) {
            labels.push(label);
            budgets.push(budget);
            mockGas.push(m);
        } else {
            assertEq(label, labels[realGas.length], "same scenario, same order");
            realGas.push(m);
        }
    }

    // ================================================================== one run

    function _run(bool real) internal {
        realToken = real;
        _deploy();
        _measureOpenAndEntries();
        uint80 r4 = _measureResolve();
        _measureClaims();
        _measureFlat(r4);
    }

    function _deploy() internal {
        strike = uint64(block.timestamp + 5 minutes);
        bell = strike + 6 hours + 30 minutes;
        token = realToken ? USDG : IUSDG(address(new MockUSDG()));
        vpm = new HunchVPM(safe, safe);
        resolver = new StockRoundResolver();
        factory = new HunchMarketFactory(vpm, resolver, IERC20Like(address(token)), safe, safe);
        feed = new MockAggregator("Robinhood NVDA / USD");
        stock = new MockStockToken("NVDA");
        vm.startPrank(safe);
        factory.setFeed(address(feed), address(stock), "NVDA", 26 hours, 26 hours, true);
        factory.setOpener(keeper, true);
        vm.stopPrank();
        _give(keeper, 1_000_000e6);
        vm.prank(keeper);
        token.approve(address(factory), type(uint256).max);
        _give(bettor, 1_000_000e6);
        vm.prank(bettor);
        token.approve(address(vpm), type(uint256).max);
    }

    function _give(address to, uint256 amount) internal {
        if (realToken) _fundUsdg(to, amount);
        else MockUSDG(address(token)).mint(to, amount);
    }

    // ------------------------------------------------------------------ the scenario of HunchGas.t.sol

    function _measureOpenAndEntries() internal {
        Measured memory m =
            _measure(keeper, address(factory), abi.encodeCall(HunchMarketFactory.openUpDown, (_upDown(strike, bell))));
        (id, specId) = abi.decode(lastReturn, (uint256, bytes32));
        _row("`openUpDown` (pull seed, create, register spec, hand over both legs, list)", m, 900_000);

        vm.roll(block.number + 1);
        _row("`enter`, first entry after creation (opens a vintage, nothing to finalize)", _enter(0, 20e6), 0);
        vm.roll(block.number + 1);
        _row(
            "`enter`, first in a new block (finalizes the previous 1-entry vintage, opens one)",
            _enter(1, 30e6),
            240_000
        );
        _row("`enter`, joining the open vintage, worst case (opens a slot of the id list)", _enter(0, 40e6), 150_000);
        _row("`enter`, joining the open vintage, typical", _enter(1, 15e6), 150_000);
        vm.roll(block.number + 1);
        vm.prank(bettor);
        vpm.enter(id, 0, 10e6); // a 1-entry vintage for the relayed entry to finalize (not measured)
        vm.roll(block.number + 1);
        _row(
            "`enterWithAuthorization`, first in a new block (finalizes a 1-entry vintage)",
            _relay(1, 50e6, "a"),
            300_000
        );
        _row("`enterWithAuthorization`, joining the open vintage", _relay(0, 25e6, "b"), 300_000);
        vm.roll(block.number + 1);
        _row(
            "`finalizeVintage` of a 2-entry vintage",
            _measure(relayer, address(vpm), abi.encodeCall(HunchVPM.finalizeVintage, (id))),
            0
        );
    }

    function _enter(uint8 o, uint256 amount) internal returns (Measured memory) {
        return _measure(bettor, address(vpm), abi.encodeCall(HunchVPM.enter, (id, o, amount)));
    }

    function _relay(uint8 o, uint256 amount, bytes32 salt) internal returns (Measured memory) {
        uint256 vb = block.timestamp + 1 hours;
        bytes32 structHash = keccak256(
            abi.encode(
                token.RECEIVE_WITH_AUTHORIZATION_TYPEHASH(),
                bettor,
                address(vpm),
                amount,
                0,
                vb,
                vpm.enterNonce(id, o, amount, salt)
            )
        );
        bytes memory sig =
            _sign(BETTOR_PK, keccak256(abi.encodePacked("\x19\x01", token.DOMAIN_SEPARATOR(), structHash)));
        return _measure(
            relayer,
            address(vpm),
            abi.encodeCall(HunchVPM.enterWithAuthorization, (bettor, id, o, amount, 0, vb, salt, sig))
        );
    }

    function _measureResolve() internal returns (uint80 r4) {
        uint80 r1 = feed.addRound(181e8, strike - 10 minutes);
        feed.addRound(183e8, strike + 1 hours);
        uint80 r3 = feed.addRound(185e8, bell - 30 minutes);
        r4 = feed.addRound(186e8, bell + 5 minutes);
        vm.roll(block.number + 1);
        vm.prank(bettor);
        vpm.enter(id, 1, 10e6); // leave a vintage open, so resolve finalizes it (the usual case)
        vm.roll(block.number + 1);
        vm.warp(bell + 60);
        _row(
            "`StockRoundResolver.resolve` (mock feed: both round proofs, oraclePaused, settler.resolve finalizing a 1-entry vintage)",
            _measure(relayer, address(resolver), abi.encodeCall(StockRoundResolver.resolve, (specId, r1, r3))),
            200_000
        );
    }

    function _measureClaims() internal {
        uint256[] memory all = vpm.marketPositions(id, 0, 20);
        // all[2]: the first UP entry, wins and pays the settler's first fee; all[4] wins too;
        // all[3]: DOWN, lost
        _row(
            "`claimFor`, winning position, first fee ever accrued in this token",
            _measure(relayer, address(vpm), abi.encodeCall(HunchVPM.claimFor, (all[2]))),
            90_000
        );
        _row(
            "`claimFor`, winning position, typical (fee balance already non-zero)",
            _measure(relayer, address(vpm), abi.encodeCall(HunchVPM.claimFor, (all[4]))),
            90_000
        );
        _row(
            "`claimFor`, losing position",
            _measure(relayer, address(vpm), abi.encodeCall(HunchVPM.claimFor, (all[3]))),
            0
        );
        _row(
            "`sweepFees` to the treasury",
            _measure(relayer, address(vpm), abi.encodeCall(HunchVPM.sweepFees, (IERC20(address(token))))),
            0
        );
    }

    function _measureFlat(uint80 r4) internal {
        uint64 f = bell + 1 days;
        vm.prank(keeper);
        (, bytes32 flatSpec) = factory.openUpDown(_upDown(f - 6 hours, f));
        uint80 last = feed.addRound(186e8, f - 2 hours); // same answer as r4
        vm.warp(f + 60);
        _row(
            "`StockRoundResolver.resolve`, FLAT (mock feed; equal answers void the market)",
            _measure(relayer, address(resolver), abi.encodeCall(StockRoundResolver.resolve, (flatSpec, r4, last))),
            0
        );
    }

    function _upDown(uint64 s, uint64 f) internal view returns (HunchMarketFactory.UpDown memory) {
        return HunchMarketFactory.UpDown({
            feed: address(feed),
            strikeTime: s,
            finalTime: f,
            maxStrikeAge: 0,
            maxFinalAge: 0,
            seedPerLeg: 10e6,
            minEntry: 1e6,
            maxEntry: 100e6
        });
    }

    // ================================================================== the real NVDA feed

    uint80 internal rfPrev;
    uint80 internal rfLatest;
    bytes32 internal rfSpec;
    bytes32 internal rfFlatSpec;

    /// @dev Two markets on the real NVDA proxy and Stock Token, with the latest real rounds as
    ///      the proofs: one that resolves (strike = the round before the latest, final = the
    ///      latest; UP or DOWN as the real prices say) and one whose strike and final are the
    ///      same round (FLAT, voids). Bounds are widened to 8 days so a weekend fork still
    ///      resolves; gas does not depend on them.
    function _realFeedRows() internal {
        _realFeedSetup();
        (uint8 st,,,,) = resolver.preview(rfSpec, rfPrev, rfLatest);
        (uint8 st2,,,,) = resolver.preview(rfFlatSpec, rfLatest, rfLatest);
        assertTrue(st >= 1 && st <= 3, "the real-feed market resolves (UP, DOWN or FLAT)");
        assertEq(st2, resolver.STATUS_FLAT(), "same round at both bells is FLAT");
        realResolve = _measure(
            relayer, address(resolver), abi.encodeCall(StockRoundResolver.resolve, (rfSpec, rfPrev, rfLatest))
        );
        realFlat = _measure(
            relayer, address(resolver), abi.encodeCall(StockRoundResolver.resolve, (rfFlatSpec, rfLatest, rfLatest))
        );
    }

    function _realFeedSetup() internal {
        RH.Ticker memory t = RH.tickers()[0];
        realToken = true;
        token = USDG;
        vpm = new HunchVPM(safe, safe);
        resolver = new StockRoundResolver();
        factory = new HunchMarketFactory(vpm, resolver, IERC20Like(RH.USDG), safe, safe);
        vm.startPrank(safe);
        factory.setFeed(t.feed, t.stockToken, "NVDA", 8 days, 8 days, true);
        factory.setOpener(keeper, true);
        vm.stopPrank();
        _give(keeper, 1_000e6);
        vm.prank(keeper);
        USDG.approve(address(factory), type(uint256).max);
        _give(bettor, 1_000e6);
        vm.prank(bettor);
        USDG.approve(address(vpm), type(uint256).max);

        IChainlinkProxy nvda = IChainlinkProxy(t.feed);
        (uint80 latest, int256 lastAnswer,, uint256 lastAt,) = nvda.latestRoundData();
        uint80 prev = latest - 1;
        (, int256 prevAnswer,, uint256 prevAt,) = nvda.getRoundData(prev);
        while (prevAt == lastAt) (, prevAnswer,, prevAt,) = nvda.getRoundData(--prev);
        (rfPrev, rfLatest) = (prev, latest);
        realFeedOutcome = lastAnswer > prevAnswer ? "UP" : lastAnswer < prevAnswer ? "DOWN" : "FLAT";

        uint64 f = uint64(block.timestamp + 1 hours);
        HunchMarketFactory.UpDown memory p = HunchMarketFactory.UpDown({
            feed: t.feed,
            // forge-lint: disable-next-line(unsafe-typecast)
            strikeTime: uint64(lastAt - 1), // a unix time fits in 64 bits
            finalTime: f,
            maxStrikeAge: 0,
            maxFinalAge: 0,
            seedPerLeg: 10e6,
            minEntry: 1e6,
            maxEntry: 100e6
        });
        vm.prank(keeper);
        uint256 m;
        (m, rfSpec) = factory.openUpDown(p);
        // forge-lint: disable-next-line(unsafe-typecast)
        p.strikeTime = uint64(lastAt);
        vm.prank(keeper);
        (, rfFlatSpec) = factory.openUpDown(p);
        vm.roll(block.number + 1);
        vm.prank(bettor);
        vpm.enter(m, 0, 10e6); // a 1-entry vintage for resolve to finalize, as in the mock row
        vm.roll(block.number + 1);
        vm.warp(f + 60);
    }

    // ================================================================== report

    function _write() internal {
        string memory md = string.concat(
            MARKER,
            "\n\n## On a fork of Robinhood Chain (4663): real USDG, real feed\n\n",
            "Generated by `RH_RPC_URL=<rpc> forge test --root contracts --match-contract ForkGasTest -vv` ",
            "(test/fork/ForkGas.t.sol) on a fork at block ",
            vm.toString(forkBlock),
            " (unix ",
            vm.toString(forkTime),
            "). The scenario of the table above, but every call runs as its own transaction (forge isolate mode), ",
            "so each figure is what its receipt shows: 21,000 base + calldata + execution, net of the EIP-3529 refund.\n\n"
        );
        md = string.concat(
            md,
            "- **mocks**: the local setup (MockUSDG, MockAggregator, MockStockToken) on the fork.\n",
            "- **real USDG**: the Paxos USDG proxy instead of MockUSDG (proxy + facets, freeze list, pause, rewards ",
            "accounting); the feed and the Stock Token stay mocks so the market resolves deterministically.\n",
            "- **execution**: real USDG, receipt gas before the refund minus 21,000 and calldata: the quantity the ",
            "budgets (docs/spec/03-contracts.md section Gas) and the local table measure.\n"
        );
        md = string.concat(
            md,
            "- The last two rows resolve on the **real NVDA Chainlink proxy** and the **real NVDA Stock Token** ",
            "(a beacon proxy), proving the latest real round and the one before it.\n\n",
            "| call | mocks (receipt) | real USDG (receipt) | real minus mocks | execution | budget | |\n",
            "|---|---:|---:|---:|---:|---:|---|\n"
        );
        for (uint256 i = 0; i < labels.length; i++) {
            md = string.concat(
                md, _line(labels[i], vm.toString(mockGas[i].receipt), realGas[i], mockGas[i].receipt, budgets[i])
            );
        }
        md = string.concat(
            md,
            _line(
                string.concat(
                    "`StockRoundResolver.resolve` on the real NVDA feed + Stock Token (latest two rounds: ",
                    realFeedOutcome,
                    ")"
                ),
                "-",
                realResolve,
                0,
                200_000
            ),
            _line(
                "`StockRoundResolver.resolve` on the real NVDA feed, FLAT (same round at both bells: voids)",
                "-",
                realFlat,
                0,
                0
            ),
            "\nReal USDG costs more than MockUSDG on every row that moves tokens (the proxy delegatecall, the facet ",
            "router, the freeze and pause checks, the rewards accounting). At the 0.02 gwei base fee observed on ",
            "chain 4663 on 2026-09-27, 1,000,000 gas costs 0.00002 ETH; the L1 data fee was 0.\n"
        );
        // forge-lint: disable-next-line(unsafe-cheatcode)
        vm.writeFile("./test/fork/GAS-FORK.md", md);
        // forge-lint: disable-next-line(unsafe-cheatcode)
        string memory gasMd = vm.readFile("./GAS.md");
        string[] memory parts = vm.split(gasMd, MARKER);
        // forge-lint: disable-next-line(unsafe-cheatcode)
        vm.writeFile("./GAS.md", string.concat(parts[0], md));
        console.log(md);
    }

    function _line(string memory label, string memory mock, Measured memory real, uint256 mockValue, uint256 budget)
        internal
        pure
        returns (string memory)
    {
        string memory delta = mockValue == 0
            ? "-"
            : real.receipt >= mockValue
                ? string.concat("+", vm.toString(real.receipt - mockValue))
                : string.concat("-", vm.toString(mockValue - real.receipt));
        string memory verdict = budget == 0 ? "" : real.execution <= budget ? "within" : "OVER";
        string memory head = string.concat("| ", label, " | ", mock, " | ", vm.toString(real.receipt), " | ", delta);
        return string.concat(
            head,
            " | ",
            vm.toString(real.execution),
            " | ",
            budget == 0 ? "-" : vm.toString(budget),
            " | ",
            verdict,
            " |\n"
        );
    }
}
