// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test, console} from "forge-std/Test.sol";
import {VestedParimutuel, IERC20} from "../src/VestedParimutuel.sol";
import {NaiveVestedParimutuel} from "../src/NaiveVestedParimutuel.sol";
import {MockERC20} from "../src/mocks/MockERC20.sol";

/// @title Gas measurements → GAS.md
/// @notice Every number is a `gasleft()` delta around one external call from this
///         contract, on cold storage (each measured call is the first touch of the
///         slots it writes in its transaction), so it is the execution cost the paper's
///         §6 talks about: it EXCLUDES the 21,000 base fee and calldata, and INCLUDES
///         the ERC-20 transfer inside the call. Run:
///           forge test --match-contract GasTest -vv
///         which rewrites GAS.md in this directory.
contract GasTest is Test {
    VestedParimutuel vpm;
    MockERC20 token;
    string md;

    uint256 constant KAPPA = 9;
    uint256 constant LEG = 5_000;
    uint64 resolutionTime;

    function setUp() public {
        token = new MockERC20();
        vpm = new VestedParimutuel();
        token.mint(address(this), 1e30);
        token.approve(address(vpm), type(uint256).max);
        vm.warp(1_000_000);
        vm.roll(100);
        resolutionTime = uint64(block.timestamp + 1 days);
    }

    // ------------------------------------------------------------------ harness

    /// @dev Reset the access lists so each measured call pays cold SLOAD/SSTORE prices,
    ///      i.e. what the same call costs as its own transaction.
    function _cold() internal {
        vm.cool(address(vpm));
        vm.cool(address(token));
    }

    function _create(uint256 n) internal returns (uint256 id, uint256 gas) {
        uint256[] memory seed = new uint256[](n);
        for (uint256 i = 0; i < n; i++) seed[i] = LEG;
        _cold();
        uint256 g = gasleft();
        id = vpm.create(IERC20(address(token)), seed, KAPPA, resolutionTime, 1 days, address(this), address(this));
        gas = g - gasleft();
    }

    function _enter(uint256 id, uint8 o, uint256 amt) internal returns (uint256 pid, uint256 gas) {
        _cold();
        uint256 g = gasleft();
        pid = vpm.enter(id, o, amt);
        gas = g - gasleft();
    }

    function _row(string memory label, uint256 gas) internal {
        md = string.concat(md, "| ", label, " | ", vm.toString(gas), " |\n");
    }

    function _table(string memory title, string memory colA) internal {
        md = string.concat(md, "\n### ", title, "\n\n| ", colA, " | gas |\n|---|---:|\n");
    }

    // ------------------------------------------------------------------ the measurement

    function test_GenerateGasReport() public {
        md = string.concat(
            "# VPM reference contract: measured gas\n\n",
            "Generated by `forge test --match-contract GasTest -vv` (test/Gas.t.sol), which rewrites this file.\n\n",
            "- solc 0.8.28, optimizer on, 200 runs, `via_ir = false`, EVM `cancun` (see foundry.toml)\n",
            "- Every figure is a `gasleft()` delta around a single external call with the contract and token storage COOLED first (`vm.cool`), i.e. the execution cost of that call as its own transaction. It excludes the 21,000 base fee and calldata, and includes the mock ERC-20 transfer inside the call.\n",
            "- kappa = 9, symmetric seed of 5,000 units per leg, stakes of 1,000 units unless stated.\n"
        );

        // ---- create
        _table("Market creation (`create`, vintage 0 with the seed clamp)", "n outcomes");
        uint256[] memory ids = new uint256[](6);
        uint256[3] memory ns = [uint256(2), 3, 5];
        for (uint256 i = 0; i < 3; i++) {
            (uint256 id, uint256 gas) = _create(ns[i]);
            ids[ns[i]] = id;
            _row(string.concat("n = ", vm.toString(ns[i])), gas);
        }

        // ---- entries
        _table("Entry (`enter`)", "case");
        for (uint256 i = 0; i < 3; i++) {
            uint256 n = ns[i];
            uint256 id = ids[n];
            vm.roll(block.number + 1);
            (, uint256 gOpen) = _enter(id, 0, 1_000); // opens the first vintage; nothing to finalize
            _row(string.concat("first entry after creation, opens a vintage, nothing to finalize (n = ", vm.toString(n), ")"), gOpen);
            vm.roll(block.number + 1);
            (, uint256 gNew) = _enter(id, 1, 1_000); // finalizes the 1-entry vintage, opens a new one
            _row(string.concat("first entry in a new block: finalizes the previous 1-entry vintage + opens (n = ", vm.toString(n), ")"), gNew);
            (, uint256 gJoin) = _enter(id, 0, 1_000); // same block
            _row(string.concat("entry joining the open vintage, same block (n = ", vm.toString(n), ")"), gJoin);
        }
        {
            uint256 id = ids[2];
            vm.warp(resolutionTime);
            _cold();
            uint256 g = gasleft();
            try vpm.enter(id, 0, 1_000) {
                revert("should have been frozen");
            } catch {}
            _row("entry refused by the freeze (reverts `Frozen`, n = 2)", g - gasleft());
            vm.warp(resolutionTime - 1);
        }

        // ---- vintage finalization vs entries in the vintage
        _table("Vintage finalization (`finalizeVintage`) by entries buffered in the vintage, n = 2", "entries");
        uint256[3] memory ks = [uint256(1), 10, 100];
        for (uint256 i = 0; i < 3; i++) {
            (uint256 id,) = _create(2);
            vm.roll(block.number + 1);
            for (uint256 j = 0; j < ks[i]; j++) vpm.enter(id, uint8(j % 2), 1_000);
            vm.roll(block.number + 1);
            _cold();
            uint256 g = gasleft();
            vpm.finalizeVintage(id);
            _row(vm.toString(ks[i]), g - gasleft());
        }

        // ---- claims
        _table("Settlement claims (n = 2)", "case");
        {
            uint256 seedPos = vpm.positionCount(); // the creator's outcome-0 seed leg
            (uint256 id,) = _create(2);
            vm.roll(block.number + 1);
            (uint256 pWin,) = _enter(id, 0, 1_000);
            vm.roll(block.number + 1);
            _enter(id, 1, 2_000);
            vm.roll(block.number + 1);
            // a partial fill to measure the refund path: N headroom is 9*7000 - 6000 = 57,000
            (uint256 pPartial,) = _enter(id, 0, 100_000);
            vm.roll(block.number + 1);
            vm.warp(resolutionTime);
            _cold();
            uint256 g = gasleft();
            vpm.resolve(id, 0);
            _row("resolve (finalizes the last 1-entry vintage)", g - gasleft());
            _cold();
            g = gasleft();
            vpm.claim(pWin);
            _row("claim, winning position", g - gasleft());
            _cold();
            g = gasleft();
            vpm.claim(pPartial);
            _row("claim, winning position with an un-withdrawn refused remainder", g - gasleft());
            vpm.claim(seedPos); // the creator's winning seed leg is the last outstanding winner
            _cold();
            g = gasleft();
            vpm.claimResidue(id);
            _row("claim residue (residue owner, after the last winner claimed)", g - gasleft());
            vm.warp(resolutionTime - 1);
        }
        {
            (uint256 id,) = _create(2);
            vm.roll(block.number + 1);
            (uint256 p,) = _enter(id, 0, 100_000); // partial fill against 40,000 of headroom
            vm.roll(block.number + 1);
            vpm.finalizeVintage(id);
            _cold();
            uint256 g = gasleft();
            vpm.withdrawRefund(p);
            _row("withdrawRefund, refused remainder of a partial fill (pre-resolution)", g - gasleft());
        }

        // ---- the naive loop form
        _table(
            "Naive Rule-1 loop form (`NaiveVestedParimutuel.enter`): one stake against an opposing book of B positions, n = 2",
            "B opposing positions"
        );
        uint256[3] memory bs = [uint256(10), 100, 1_000];
        for (uint256 i = 0; i < 3; i++) {
            uint256[] memory seed = new uint256[](2);
            seed[0] = 1e9;
            seed[1] = 1e9; // deep books so nothing is refused while filling
            NaiveVestedParimutuel naive = new NaiveVestedParimutuel(IERC20(address(token)), KAPPA, seed);
            token.approve(address(naive), type(uint256).max);
            for (uint256 j = 1; j < bs[i]; j++) naive.enter(1, 1e6); // book 1 = seed leg + (B-1) positions
            naive.enter(0, 1e9); // warm-up: every opposing position now holds a non-zero vested claim
            vm.cool(address(naive));
            vm.cool(address(token));
            uint256 g = gasleft();
            naive.enter(0, 1e9); // vests into all B positions on book 1: one non-zero SSTORE each
            _row(vm.toString(bs[i]), g - gasleft());
        }
        md = string.concat(
            md,
            "\nThe accumulator form's entry cost is flat in the book size (see the entry table); the loop form grows by roughly 5,000 gas per opposing position, matching the per-position SSTORE the paper's section 6 cites.\n"
        );

        vm.writeFile("./GAS.md", md);
        console.log(md);
    }
}
