// GENERATED by scripts/wire-deployment.mjs from deployments/robinhood-mainnet.json.
// Do not edit by hand: edit the JSON, then run `pnpm exec node scripts/wire-deployment.mjs --write`.
import type { Deployment } from './types.js';

export const EMBEDDED_DEPLOYMENT: Deployment = {
  "network": "robinhood-mainnet",
  "chainId": 4663,
  "status": "deployed",
  "deployedAt": "2026-10-02T17:56:22Z",
  "gitCommit": "c8aac85c325179fc48309859df0c5aafe13fd27d",
  "startBlock": 78426641,
  "contracts": {
    "HunchVPM": {
      "address": "0x1c23356536eA8E30F53481b971098aC30DA43576",
      "deployTx": "0x3a007ba9e76c889caabbe9049c957f482e9bd26703217fc9168e55344e880bf9",
      "block": 78426658
    },
    "StockRoundResolver": {
      "address": "0xb3336ab62cB57841CDEA2CA43d62F2D2c5287721",
      "deployTx": "0x5deadfcf523257da629b38ac8ab8be3fc06d3e885facd354de19e3c1abeb269b",
      "block": 78426641
    },
    "HunchMarketFactory": {
      "address": "0x2EdcCA1e40AEACD3ef2d5FcBFEAC5B356e1b6676",
      "deployTx": "0xc67939506d4308ed9042f3fe0caac5509e734854c4773aa7107a9419d9329f27",
      "block": 78426671
    }
  },
  "safe": "0x5866308Af35fA8AbD67f88d31695aD029143F336",
  "keeper": "0xEb420AD181518814B6E3feb89A9d369Da3F5b580",
  "usdg": "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
  "multicall3": "0xcA11bde05977b3631167028862bE2a173976CA11",
  "explorer": "https://robinhoodchain.blockscout.com",
  "params": {
    "kappa": 30,
    "feeBps": 200,
    "voidTimeoutSec": 259200,
    "seedPerLeg": "1000000",
    "minEntry": "1000000",
    "maxEntry": "25000000"
  },
  "feeds": [
    {
      "ticker": "NVDA",
      "feed": "0x379EC4f7C378F34a1B47E4F3cbeBCbAC3E8E9F15",
      "aggregator": "0xC9d16E4f2569b9E3ea0468fD85844953713DC2a2",
      "stockToken": "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC",
      "maxStrikeAge": 93600,
      "maxFinalAge": 93600,
      "families": [
        "daily"
      ]
    },
    {
      "ticker": "TSLA",
      "feed": "0x4A1166a659A55625345e9515b32adECea5547C38",
      "aggregator": "0x7A6b81ba7FbCB90104d8C496158Cf383cD7233b1",
      "stockToken": "0x322F0929c4625eD5bAd873c95208D54E1c003b2d",
      "maxStrikeAge": 93600,
      "maxFinalAge": 93600,
      "families": [
        "daily"
      ]
    },
    {
      "ticker": "AAPL",
      "feed": "0x6B22A786bAa607d76728168703a39Ea9C99f2cD0",
      "aggregator": "0xBb11A21267cFDb63d4935d99a499133DD1744ACb",
      "stockToken": "0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9",
      "maxStrikeAge": 93600,
      "maxFinalAge": 93600,
      "families": []
    },
    {
      "ticker": "COIN",
      "feed": "0xA3a468A452940B7D6b69991207B508c609a98Ef2",
      "aggregator": "0x30398b0B0df82a009bB2D507BC7fE1dc6d3ca294",
      "stockToken": "0x6330D8C3178a418788dF01a47479c0ce7CCF450b",
      "maxStrikeAge": 93600,
      "maxFinalAge": 93600,
      "families": [],
      "pendingFlatRateCheck": false
    }
  ]
};
