// GENERATED by scripts/wire-deployment.mjs from deployments/robinhood-mainnet.json.
// Do not edit by hand: edit the JSON, then run `pnpm exec node scripts/wire-deployment.mjs --write`.
import type { Deployment } from './types.js';

export const EMBEDDED_DEPLOYMENT: Deployment = {
  "network": "robinhood-mainnet",
  "chainId": 4663,
  "status": "not-deployed",
  "deployedAt": null,
  "gitCommit": null,
  "startBlock": null,
  "contracts": {
    "HunchVPM": {
      "address": "0x0000000000000000000000000000000000000000",
      "deployTx": null,
      "block": null
    },
    "StockRoundResolver": {
      "address": "0x0000000000000000000000000000000000000000",
      "deployTx": null,
      "block": null
    },
    "HunchMarketFactory": {
      "address": "0x0000000000000000000000000000000000000000",
      "deployTx": null,
      "block": null
    }
  },
  "safe": "0x0000000000000000000000000000000000000000",
  "keeper": "0x0000000000000000000000000000000000000000",
  "usdg": "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168",
  "multicall3": "0xcA11bde05977b3631167028862bE2a173976CA11",
  "explorer": "https://robinhoodchain.blockscout.com",
  "params": {
    "kappa": 30,
    "feeBps": 200,
    "voidTimeoutSec": 259200,
    "seedPerLeg": "10000000",
    "minEntry": "1000000",
    "maxEntry": "100000000"
  },
  "feeds": [
    {
      "ticker": "NVDA",
      "feed": "0x379EC4f7C378F34a1B47E4F3cbeBCbAC3E8E9F15",
      "aggregator": "0xC9d16E4f2569b9E3ea0468fD85844953713DC2a2",
      "stockToken": "0xd0601CE157Db5bdC3162BbaC2a2C8aF5320D9EEC",
      "maxStrikeAge": 93600,
      "maxFinalAge": 93600,
      "families": [
        "daily",
        "weekly"
      ]
    },
    {
      "ticker": "TSLA",
      "feed": "0x4A1166a659A55625345e9515b32adECea5547C38",
      "aggregator": "0x7A6b81ba7FbCB90104d8C496158Cf383cD7233b1",
      "stockToken": "0x322F0929c4625eD5bAd873c95208D54E1c003b2d",
      "maxStrikeAge": 93600,
      "maxFinalAge": 93600,
      "families": [
        "daily",
        "weekly"
      ]
    },
    {
      "ticker": "AAPL",
      "feed": "0x6B22A786bAa607d76728168703a39Ea9C99f2cD0",
      "aggregator": "0xBb11A21267cFDb63d4935d99a499133DD1744ACb",
      "stockToken": "0xaF3D76f1834A1d425780943C99Ea8A608f8a93f9",
      "maxStrikeAge": 93600,
      "maxFinalAge": 93600,
      "families": [
        "daily",
        "weekly"
      ]
    },
    {
      "ticker": "COIN",
      "feed": "0xA3a468A452940B7D6b69991207B508c609a98Ef2",
      "aggregator": "0x30398b0B0df82a009bB2D507BC7fE1dc6d3ca294",
      "stockToken": "0x6330D8C3178a418788dF01a47479c0ce7CCF450b",
      "maxStrikeAge": 93600,
      "maxFinalAge": 93600,
      "families": [
        "daily",
        "weekly"
      ],
      "pendingFlatRateCheck": true
    }
  ]
};
