// This file is @generated by prost-build.
/// Where a row came from, so a row can be traced back to its log.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Meta {
    #[prost(uint64, tag = "1")]
    pub block_number: u64,
    #[prost(uint64, tag = "2")]
    pub timestamp: u64,
    #[prost(string, tag = "3")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub log_index: u64,
    /// The substreams ordinal of the log within the block. Used as the change ordinal in
    /// db_out so two updates to the same row in one block are applied in log order.
    #[prost(uint64, tag = "5")]
    pub ordinal: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Markets {
    #[prost(message, repeated, tag = "1")]
    pub markets: ::prost::alloc::vec::Vec<Market>,
    #[prost(message, repeated, tag = "2")]
    pub specs: ::prost::alloc::vec::Vec<ResolutionSpec>,
    #[prost(message, repeated, tag = "3")]
    pub readings: ::prost::alloc::vec::Vec<FeedReading>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Market {
    /// "{settler}-{market_id}"
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "MarketOp", tag = "2")]
    pub op: i32,
    #[prost(enumeration = "SettlementRule", tag = "3")]
    pub rule: i32,
    #[prost(string, tag = "4")]
    pub settler: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub market_id: u64,
    #[prost(string, tag = "6")]
    pub creator: ::prost::alloc::string::String,
    /// n = |O|
    #[prost(uint32, tag = "7")]
    pub outcomes: u32,
    #[prost(string, tag = "8")]
    pub kappa: ::prost::alloc::string::String,
    /// kappa == 2^256-1 is the settler's sentinel for an unbounded capacity coefficient,
    /// which is the prescription for n-way markets. A book with it never refuses stake.
    #[prost(bool, tag = "9")]
    pub kappa_unbounded: bool,
    #[prost(uint64, tag = "10")]
    pub resolution_time: u64,
    #[prost(enumeration = "MarketStatus", tag = "11")]
    pub status: i32,
    /// -1 until resolved
    #[prost(int32, tag = "12")]
    pub winner: i32,
    /// set when the market was opened through MarketFactory
    #[prost(string, tag = "13")]
    pub spec_id: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub opener: ::prost::alloc::string::String,
    /// offered per outcome, from MarketFactory.MarketOpened
    #[prost(string, repeated, tag = "15")]
    pub seed: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "16")]
    pub meta: ::core::option::Option<Meta>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResolutionSpec {
    /// specId, the hash of the whole spec
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub settler: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub market_id: u64,
    /// "{settler}-{market_id}"
    #[prost(string, tag = "4")]
    pub market: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub oracle: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub feed_key: ::prost::alloc::string::String,
    /// int256 at 8 decimals
    #[prost(string, tag = "7")]
    pub strike: ::prost::alloc::string::String,
    /// 0 = above (inclusive of the strike), 1 = below
    #[prost(uint32, tag = "8")]
    pub direction: u32,
    #[prost(uint64, tag = "9")]
    pub resolution_time: u64,
    #[prost(uint64, tag = "10")]
    pub max_staleness: u64,
    /// the FeedResolver that holds the spec
    #[prost(string, tag = "11")]
    pub resolver: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "12")]
    pub meta: ::core::option::Option<Meta>,
}
/// What the resolver read when it settled or voided. Kept separate from the market row
/// because a stale feed voids the market, and the age that caused it is worth auditing.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FeedReading {
    /// "{spec_id}-{block_number}-{log_index}"
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub spec_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub resolver: ::prost::alloc::string::String,
    /// VoidedStale(bytes32 specId, uint256 age) carries neither of the next two: the whole
    /// point of that event is that the reading could not be trusted. market_id stays 0 and
    /// winner is the -1 sentinel, and db_out writes neither column, because 0 is a real
    /// market id and a real outcome.
    #[prost(uint64, tag = "4")]
    pub market_id: u64,
    #[prost(bool, tag = "5")]
    pub voided_stale: bool,
    /// -1 on a stale void
    #[prost(int32, tag = "6")]
    pub winner: i32,
    /// int256 at 8 decimals; empty on a stale void
    #[prost(string, tag = "7")]
    pub price: ::prost::alloc::string::String,
    /// the feed's own timestamp; 0 and unwritten on a stale void
    #[prost(uint64, tag = "8")]
    pub updated_at: u64,
    /// seconds, only on a stale void
    #[prost(uint64, tag = "9")]
    pub age: u64,
    #[prost(message, optional, tag = "10")]
    pub meta: ::core::option::Option<Meta>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Positions {
    #[prost(message, repeated, tag = "1")]
    pub positions: ::prost::alloc::vec::Vec<Position>,
    #[prost(message, repeated, tag = "2")]
    pub vintages: ::prost::alloc::vec::Vec<Vintage>,
    #[prost(message, repeated, tag = "3")]
    pub settlements: ::prost::alloc::vec::Vec<Settlement>,
    #[prost(message, repeated, tag = "4")]
    pub residues: ::prost::alloc::vec::Vec<Residue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Position {
    /// "{settler}-{position_id}"
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(enumeration = "PositionOp", tag = "2")]
    pub op: i32,
    #[prost(enumeration = "SettlementRule", tag = "3")]
    pub rule: i32,
    #[prost(string, tag = "4")]
    pub settler: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub position_id: u64,
    #[prost(string, tag = "6")]
    pub market: ::prost::alloc::string::String,
    #[prost(uint64, tag = "7")]
    pub market_id: u64,
    #[prost(string, tag = "8")]
    pub owner: ::prost::alloc::string::String,
    #[prost(uint32, tag = "9")]
    pub outcome: u32,
    /// c_k, the amount offered at entry
    #[prost(string, tag = "10")]
    pub offered: ::prost::alloc::string::String,
    /// the block number whose entries share a vintage
    #[prost(uint64, tag = "11")]
    pub vintage: u64,
    /// vintage 0, the creator's leg, posted inside create()
    #[prost(bool, tag = "12")]
    pub seed: bool,
    /// POSITION_OP_SETTLE only, and per-log rather than cumulative: db_out accumulates
    /// them into the position's totals. There is deliberately no "claimed" flag — a
    /// Claimed log with payout 0 is either a losing position settling or a refused
    /// remainder being withdrawn, and nothing in the log tells the two apart.
    #[prost(string, tag = "13")]
    pub payout: ::prost::alloc::string::String,
    /// offered - accepted, the part a book refused
    #[prost(string, tag = "14")]
    pub refund: ::prost::alloc::string::String,
    /// The seed legs are logged in the same transaction as MarketCreated, so a book has to
    /// be opened before any store has seen the market. These carry n and kappa forward from
    /// the same block; they are empty for an entry into a market created earlier.
    #[prost(uint32, tag = "16")]
    pub outcomes_hint: u32,
    #[prost(string, tag = "17")]
    pub kappa_hint: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "18")]
    pub meta: ::core::option::Option<Meta>,
}
/// A vintage is the set of entries sharing a block. They never vest into each other, and
/// the settler finalizes them lazily, so meta here is the FINALIZING block, not the
/// vintage block. `vintage` is the vintage block number.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Vintage {
    /// "{settler}-{market_id}-{vintage}"
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub market: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub settler: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub market_id: u64,
    #[prost(uint64, tag = "5")]
    pub vintage: u64,
    #[prost(uint64, tag = "6")]
    pub entries: u64,
    #[prost(message, optional, tag = "7")]
    pub meta: ::core::option::Option<Meta>,
}
/// An append-only ledger of Claimed logs. A position emits at most two: withdrawRefund
/// pays the refused remainder alone, claim pays the settlement and any remainder left.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Settlement {
    /// "{settler}-{position_id}-{block_number}-{log_index}"
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub position: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub settler: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub position_id: u64,
    #[prost(string, tag = "5")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub payout: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub refund: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub meta: ::core::option::Option<Meta>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Residue {
    /// "{settler}-{market_id}"
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub market: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub settler: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub market_id: u64,
    #[prost(string, tag = "5")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub amount: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub meta: ::core::option::Option<Meta>,
}
/// Held by store_positions so store_books can attribute a Claimed log, which carries only
/// a position id, back to the book whose principal that refund has to come out of.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PositionRef {
    #[prost(string, tag = "1")]
    pub settler: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub market_id: u64,
    #[prost(uint32, tag = "3")]
    pub outcome: u32,
    #[prost(string, tag = "4")]
    pub offered: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookDeltas {
    #[prost(message, repeated, tag = "1")]
    pub deltas: ::prost::alloc::vec::Vec<BookDelta>,
}
/// One row per book per block in which that book moved. headroom = capacity - vested is
/// the room the book still has to accept stake; when it runs out a stake is refused and
/// refunded rather than reverted.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BookDelta {
    /// "{book}-{block_number}"
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// "{settler}-{market_id}-{outcome}"
    #[prost(string, tag = "2")]
    pub book: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub market: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub settler: ::prost::alloc::string::String,
    #[prost(uint64, tag = "5")]
    pub market_id: u64,
    #[prost(uint32, tag = "6")]
    pub outcome: u32,
    /// P_w
    #[prost(string, tag = "7")]
    pub principal: ::prost::alloc::string::String,
    /// V_w
    #[prost(string, tag = "8")]
    pub vested: ::prost::alloc::string::String,
    /// C_w = kappa * P_w; empty when kappa is unbounded
    #[prost(string, tag = "9")]
    pub capacity: ::prost::alloc::string::String,
    /// H_w = C_w - V_w, floored at 0; empty when unbounded
    #[prost(string, tag = "10")]
    pub headroom: ::prost::alloc::string::String,
    #[prost(bool, tag = "11")]
    pub unbounded: bool,
    #[prost(string, tag = "12")]
    pub principal_delta: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub vested_delta: ::prost::alloc::string::String,
    /// The classic rule has neither vesting nor capacity, so a classic book carries a
    /// principal and nothing else. The rule says which columns mean anything.
    #[prost(enumeration = "SettlementRule", tag = "15")]
    pub rule: i32,
    /// A book moves as an aggregate of every log in the block, so meta here carries the
    /// block and its timestamp; tx_hash and log_index are empty.
    #[prost(message, optional, tag = "14")]
    pub meta: ::core::option::Option<Meta>,
}
/// Which settlement rule a market runs under. The two settlers share an interface and
/// most of their event set; they are told apart by which contract emitted the log, not
/// by anything inside the log.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SettlementRule {
    Unspecified = 0,
    Vested = 1,
    Classic = 2,
}
impl SettlementRule {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SETTLEMENT_RULE_UNSPECIFIED",
            Self::Vested => "SETTLEMENT_RULE_VESTED",
            Self::Classic => "SETTLEMENT_RULE_CLASSIC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SETTLEMENT_RULE_UNSPECIFIED" => Some(Self::Unspecified),
            "SETTLEMENT_RULE_VESTED" => Some(Self::Vested),
            "SETTLEMENT_RULE_CLASSIC" => Some(Self::Classic),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MarketStatus {
    Unspecified = 0,
    Open = 1,
    Resolved = 2,
    Voided = 3,
}
impl MarketStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MARKET_STATUS_UNSPECIFIED",
            Self::Open => "MARKET_STATUS_OPEN",
            Self::Resolved => "MARKET_STATUS_RESOLVED",
            Self::Voided => "MARKET_STATUS_VOIDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MARKET_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "MARKET_STATUS_OPEN" => Some(Self::Open),
            "MARKET_STATUS_RESOLVED" => Some(Self::Resolved),
            "MARKET_STATUS_VOIDED" => Some(Self::Voided),
            _ => None,
        }
    }
}
/// Which columns of a market row the emitting event actually knows. A Resolved log
/// carries the winner and nothing else, so the sink must update rather than replace.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MarketOp {
    Unspecified = 0,
    Create = 1,
    LinkSpec = 2,
    Resolve = 3,
    Void = 4,
}
impl MarketOp {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MARKET_OP_UNSPECIFIED",
            Self::Create => "MARKET_OP_CREATE",
            Self::LinkSpec => "MARKET_OP_LINK_SPEC",
            Self::Resolve => "MARKET_OP_RESOLVE",
            Self::Void => "MARKET_OP_VOID",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MARKET_OP_UNSPECIFIED" => Some(Self::Unspecified),
            "MARKET_OP_CREATE" => Some(Self::Create),
            "MARKET_OP_LINK_SPEC" => Some(Self::LinkSpec),
            "MARKET_OP_RESOLVE" => Some(Self::Resolve),
            "MARKET_OP_VOID" => Some(Self::Void),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PositionOp {
    Unspecified = 0,
    Enter = 1,
    Transfer = 2,
    Settle = 3,
}
impl PositionOp {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "POSITION_OP_UNSPECIFIED",
            Self::Enter => "POSITION_OP_ENTER",
            Self::Transfer => "POSITION_OP_TRANSFER",
            Self::Settle => "POSITION_OP_SETTLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "POSITION_OP_UNSPECIFIED" => Some(Self::Unspecified),
            "POSITION_OP_ENTER" => Some(Self::Enter),
            "POSITION_OP_TRANSFER" => Some(Self::Transfer),
            "POSITION_OP_SETTLE" => Some(Self::Settle),
            _ => None,
        }
    }
}
