#!/usr/bin/env node
// Generates packages/client/src/abi/generated/*.ts from the Foundry build output, so the
// client's ABIs can never drift from the contracts that get deployed.
//
//   pnpm exec node scripts/gen-abis.mjs           write the generated files
//   pnpm exec node scripts/gen-abis.mjs --check   fail if they differ from contracts/out (CI)
//
// Plain Node ESM, no dependencies. Run `forge build --root contracts` first. If
// contracts/out does not exist the script prints a notice and exits 0 (the client then
// uses the hand-written frozen interfaces). A contract not yet compiled keeps its
// hand-written ABI; generated/index.ts records which source each export comes from.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'contracts', 'out');
const GEN = join(ROOT, 'packages', 'client', 'src', 'abi', 'generated');

const CONTRACTS = [
  { name: 'HunchVPM', exportName: 'hunchVpmAbi' },
  { name: 'StockRoundResolver', exportName: 'stockRoundResolverAbi' },
  { name: 'HunchMarketFactory', exportName: 'hunchMarketFactoryAbi' },
];

const args = new Set(process.argv.slice(2));
const CHECK = args.has('--check');
for (const a of args) {
  if (a !== '--check') {
    console.error(`unknown argument ${a}`);
    process.exit(2);
  }
}

const rel = (p) => relative(ROOT, p);
const HEADER = (source) =>
  [
    `// GENERATED by scripts/gen-abis.mjs from ${source}. Do not edit by hand:`,
    '// run `forge build --root contracts && pnpm exec node scripts/gen-abis.mjs`.',
  ].join('\n');

/** Keep only the ABI-relevant keys, in a fixed order, so output is stable across forge versions. */
function normalize(abi) {
  const clean = (x) => {
    if (Array.isArray(x)) return x.map(clean);
    if (x === null || typeof x !== 'object') return x;
    const order = ['type', 'name', 'inputs', 'outputs', 'stateMutability', 'anonymous', 'indexed', 'internalType', 'components'];
    const out = {};
    for (const k of order) if (k in x) out[k] = clean(x[k]);
    return out;
  };
  return abi.map(clean);
}

function renderAbiFile(c, abi, source) {
  return `${HEADER(source)}\n\nexport const ${c.exportName}Generated = ${JSON.stringify(normalize(abi), null, 2)} as const;\n`;
}

function renderIndex(present) {
  const lines = [HEADER('contracts/out (see scripts/gen-abis.mjs)'), ''];
  for (const c of CONTRACTS) {
    if (present.has(c.name)) {
      lines.push(`export { ${c.exportName}Generated as ${c.exportName} } from './${c.name}.js';`);
    } else {
      lines.push(`// ${c.name}: not in contracts/out yet, the hand-written frozen interface is exported instead.`);
      lines.push(`export { ${c.exportName}Handwritten as ${c.exportName} } from '../handwritten.js';`);
    }
  }
  lines.push(`export const GENERATED_FROM_CONTRACTS_OUT = ${JSON.stringify([...present].sort())} as const;`);
  return `${lines.join('\n')}\n`;
}

function main() {
  if (!existsSync(OUT)) {
    console.log('gen-abis: contracts/out does not exist (run `forge build --root contracts`); keeping the current ABIs');
    return;
  }
  const expected = new Map();
  const present = new Set();
  for (const c of CONTRACTS) {
    const artifact = join(OUT, `${c.name}.sol`, `${c.name}.json`);
    if (!existsSync(artifact)) {
      console.log(`gen-abis: ${rel(artifact)} not built yet; ${c.exportName} stays hand-written`);
      continue;
    }
    const json = JSON.parse(readFileSync(artifact, 'utf8'));
    if (!Array.isArray(json.abi)) {
      console.error(`gen-abis: ${rel(artifact)} has no abi array`);
      process.exit(1);
    }
    present.add(c.name);
    expected.set(join(GEN, `${c.name}.ts`), renderAbiFile(c, json.abi, `contracts/out/${c.name}.sol/${c.name}.json`));
  }
  expected.set(join(GEN, 'index.ts'), renderIndex(present));

  const drift = [];
  for (const [path, content] of expected) {
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (current === content) continue;
    if (CHECK) drift.push(rel(path));
    else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, content);
      console.log(`gen-abis: wrote ${rel(path)}`);
    }
  }
  if (drift.length > 0) {
    console.error(`gen-abis: client ABIs differ from contracts/out:\n  - ${drift.join('\n  - ')}\nrun: pnpm exec node scripts/gen-abis.mjs`);
    process.exit(1);
  }
  console.log(`gen-abis: ${CHECK ? 'ABIs match' : 'ABIs up to date with'} contracts/out (${[...present].join(', ') || 'none built'})`);
}

main();
