import { parseAbi } from 'viem';

/**
 * Hand-written from the FROZEN INTERFACES in .ocean/PLAN.md, before `contracts/out`
 * existed. `scripts/gen-abis.mjs` writes the compiler's ABIs to `./generated/`, and
 * `./index.ts` exports those once they exist; this file stays as the reference the
 * generated ABIs are tested against (every function here must exist there with the
 * same inputs and outputs).
 */

export const hunchVpmAbiHandwritten = parseAbi([
  'struct Book { uint256 principal; uint256 acc; uint256 capacity; uint256 vested; uint256 demand; uint256 live; }',
  // constants and immutables
  'function SCALE() view returns (uint256)',
  'function KAPPA_UNBOUNDED() view returns (uint256)',
  'function ENTER_TYPEHASH() view returns (bytes32)',
  'function guardian() view returns (address)',
  'function factory() view returns (address)',
  'function pauser() view returns (address)',
  'function treasury() view returns (address)',
  'function entriesPaused() view returns (bool)',
  'function feesAccrued(address token) view returns (uint256)',
  // lifecycle
  'function create(address token, uint256[] seed, uint256 kappa, uint64 resolutionTime, uint64 voidTimeout, address resolver, address residueOwner, uint16 feeBps, uint128 minEntry, uint128 maxEntry) returns (uint256 marketId)',
  'function enter(uint256 marketId, uint8 outcome, uint256 amount) returns (uint256 positionId)',
  'function enterNonce(uint256 marketId, uint8 outcome, uint256 amount, bytes32 salt) view returns (bytes32)',
  'function enterWithAuthorization(address from, uint256 marketId, uint8 outcome, uint256 amount, uint256 validAfter, uint256 validBefore, bytes32 salt, bytes signature) returns (uint256 positionId)',
  'function finalizeVintage(uint256 marketId)',
  'function resolve(uint256 marketId, uint8 winner)',
  'function voidMarket(uint256 marketId)',
  'function withdrawRefund(uint256 positionId)',
  'function withdrawRefundFor(uint256 positionId)',
  'function claim(uint256 positionId)',
  'function claimFor(uint256 positionId)',
  'function claimResidue(uint256 marketId)',
  'function sweepFees(address token)',
  'function transferPosition(uint256 positionId, address to)',
  'function setEntriesPaused(bool paused)',
  'function setPauser(address pauser)',
  // views
  'function marketCount() view returns (uint256)',
  'function positionCount() view returns (uint256)',
  'function positions(uint256 positionId) view returns (uint64 marketId, address owner, uint8 outcome, bool finalized, bool refunded, bool claimed, uint64 vintage, uint128 offered, uint128 accepted, uint128 entryAcc)',
  'function getMarket(uint256 marketId) view returns (address token, address creator, address resolver, address residueOwner, uint64 resolutionTime, uint64 voidTimeout, uint8 n, uint8 status, uint8 winner, uint256 kappa, uint256 acceptedPool, uint256 paidOut)',
  'function marketTerms(uint256 marketId) view returns (uint16 feeBps, uint128 minEntry, uint128 maxEntry)',
  'function getBook(uint256 marketId, uint8 outcome) view returns (Book)',
  'function pendingCount(uint256 marketId) view returns (uint256)',
  'function headroom(uint256 marketId, uint8 outcome) view returns (uint256)',
  'function previewPayout(uint256 positionId) view returns (uint256)',
  'function accrued(uint256 positionId) view returns (uint256)',
  'function previewFee(uint256 positionId) view returns (uint256)',
  'function marketPositions(uint256 marketId, uint256 from, uint256 count) view returns (uint256[] ids)',
  'function marketPositionCount(uint256 marketId) view returns (uint256)',
  // events
  'event MarketCreated(uint256 indexed marketId, address indexed creator, uint8 n, uint256 kappa, uint64 resolutionTime)',
  'event Entered(uint256 indexed marketId, uint256 indexed positionId, address indexed owner, uint8 outcome, uint256 offered, uint64 vintage)',
  'event VintageFinalized(uint256 indexed marketId, uint64 indexed vintage, uint256 entries)',
  'event Resolved(uint256 indexed marketId, uint8 winner)',
  'event Voided(uint256 indexed marketId)',
  'event Claimed(uint256 indexed positionId, address indexed to, uint256 payout, uint256 refund)',
  'event ResidueClaimed(uint256 indexed marketId, address indexed to, uint256 amount)',
  'event PositionTransferred(uint256 indexed positionId, address indexed from, address indexed to)',
  'event FeeAccrued(uint256 indexed positionId, uint256 fee)',
  'event FeesSwept(address indexed token, address indexed to, uint256 amount)',
  'event EntriesPaused(bool paused)',
  // errors
  'error InvalidKappa()',
  'error InvalidSeed()',
  'error InvalidOutcomes()',
  'error BadResolutionTime()',
  'error Frozen()',
  'error NotOpen()',
  'error NotSettled()',
  'error NotResolver()',
  'error TooEarly()',
  'error NotOwner()',
  'error AlreadyClaimed()',
  'error NothingToRefund()',
  'error NotFinalized()',
  'error NotResidueOwner()',
  'error WinnersOutstanding()',
  'error ClampDidNotConverge()',
  'error TransferFailed()',
  'error Reentrancy()',
  'error AmountTooLarge()',
  'error FeeTooHigh()',
  'error EntryTooSmall()',
  'error EntryTooLarge()',
  'error EntriesArePaused()',
]);

export const stockRoundResolverAbiHandwritten = parseAbi([
  'struct Spec { address settler; uint256 marketId; address feed; address stockToken; uint64 strikeTime; uint64 finalTime; uint32 maxStrikeAge; uint32 maxFinalAge; }',
  'function register(Spec spec) returns (bytes32 specId)',
  'function resolve(bytes32 specId, uint80 strikeRound, uint80 finalRound)',
  'function voidStale(bytes32 specId, uint80 strikeRound, uint80 finalRound)',
  'function voidBadAnswer(bytes32 specId, uint80 strikeRound, uint80 finalRound)',
  'function voidPaused(bytes32 specId)',
  'function preview(bytes32 specId, uint80 strikeRound, uint80 finalRound) view returns (uint8 status, int256 strikeAnswer, uint256 strikeAt, int256 finalAnswer, uint256 finalAt)',
  'function getSpec(bytes32 specId) view returns (Spec)',
  'function settled(bytes32 specId) view returns (bool)',
  'function specIdOf(address settler, uint256 marketId) view returns (bytes32)',
  'event Registered(bytes32 indexed specId, address indexed settler, uint256 indexed marketId, address feed, address stockToken, uint64 strikeTime, uint64 finalTime, uint32 maxStrikeAge, uint32 maxFinalAge)',
  'event Resolved(bytes32 indexed specId, uint256 indexed marketId, uint8 outcome, uint80 strikeRound, int256 strikeAnswer, uint256 strikeAt, uint80 finalRound, int256 finalAnswer, uint256 finalAt)',
  'event VoidedStale(bytes32 indexed specId, uint256 indexed marketId, uint80 strikeRound, uint80 finalRound)',
  'event VoidedPaused(bytes32 indexed specId, uint256 indexed marketId)',
  'error BadProof()',
  'error PhaseBoundary()',
  'error OraclePaused()',
  'error Stale()',
  'error NotStale()',
  'error AlreadySettled()',
  'error TooEarly()',
]);

export const hunchMarketFactoryAbiHandwritten = parseAbi([
  'struct UpDown { address feed; uint64 strikeTime; uint64 finalTime; uint32 maxStrikeAge; uint32 maxFinalAge; uint128 seedPerLeg; uint128 minEntry; uint128 maxEntry; }',
  'function settler() view returns (address)',
  'function resolver() view returns (address)',
  'function usdg() view returns (address)',
  'function treasury() view returns (address)',
  'function owner() view returns (address)',
  'function pendingOwner() view returns (address)',
  'function openers(address opener) view returns (bool)',
  'function KAPPA() view returns (uint256)',
  'function FEE_BPS() view returns (uint16)',
  'function VOID_TIMEOUT() view returns (uint64)',
  'function MAX_WINDOW() view returns (uint256)',
  'function feeds(address feed) view returns (address stockToken, uint32 maxStrikeAge, uint32 maxFinalAge, bool allowed, string ticker)',
  'function feedCount() view returns (uint256)',
  'function feedAt(uint256 i) view returns (address)',
  'function openUpDown(UpDown p) returns (uint256 marketId, bytes32 specId)',
  'function listingCount() view returns (uint256)',
  'function listings(uint256 i) view returns (uint256 marketId, bytes32 specId, address feed, uint64 strikeTime, uint64 finalTime, uint32 maxStrikeAge, uint32 maxFinalAge, uint128 seedPerLeg, uint128 minEntry, uint128 maxEntry, address opener, uint64 openedAt)',
  'function listingIndexOf(uint256 marketId) view returns (uint256)',
  'function setFeed(address feed, address stockToken, string ticker, uint32 maxStrikeAge, uint32 maxFinalAge, bool allowed)',
  'function setOpener(address opener, bool allowed)',
  'function transferOwnership(address newOwner)',
  'function acceptOwnership()',
  'event MarketOpened(uint256 indexed marketId, bytes32 indexed specId, address indexed feed, string ticker, uint64 strikeTime, uint64 finalTime, uint128 seedPerLeg, uint128 minEntry, uint128 maxEntry)',
  'event FeedSet(address indexed feed, address indexed stockToken, string ticker, uint32 maxStrikeAge, uint32 maxFinalAge, bool allowed)',
  'event OpenerSet(address indexed opener, bool allowed)',
  'event OwnershipTransferStarted(address indexed previousOwner, address indexed newOwner)',
  'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
]);
